
// This file has been generated by the GUI designer. Do not modify.
namespace cinemaman
{
	public partial class LeftFrame
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget cinemaman.LeftFrame
			global::Stetic.BinContainer.Attach (this);
			this.Name = "cinemaman.LeftFrame";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
