
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		global::Stetic.BinContainer.Attach (this);
		this.Name = "MainWindow";
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Hide ();
	}
}
